apiVersion: apps/v1
kind: Deployment
metadata:
  name: type-11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: type-11
  template:
    metadata:
      labels:
        app: type-11
    spec:
      containers:
        - name: type-11
          image: docker.io/timattt/type-11:latest
          imagePullPolicy: Always
          env:
            - name: TYPE6_DATABASE_USER
              value: default-user
            - name: TYPE6_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_6_database_jdbc_url
            - name: TYPE6_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: type-6-basic-secrets
                  key: type_6_database_password