version: '3.4'
name: type-11-infrastructure
services:
  postgres:
    container_name: type-11-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 1s
      timeout: 1s
      retries: 100
    user: postgres
    command: ["postgres", "-c", "log_statement=all"]
    profiles:
      - local
      - dockerized
  envoy:
    container_name: type-11-envoy
    image: envoyproxy/envoy:dev-1ffd4522cdb86ac62ad307d8f28a166e5261411b
    ports:
      - "8080:8080"
      - "8081:8081"
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      default:
    profiles:
      - dockerized
  type-11:
    container_name: type-11
    build:
      context: ./../../.
    ports:
      - "9090:9090"
    networks:
      default:
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: "dockerized"
    profiles:
      - dockerized
  type-6:
    container_name: type-6
    image: quay.io/timattt/type-6
    ports:
      - "7777:7777"
    volumes:
      - "./keys:/tmp/keys"
    environment:
      SPRING_PROFILES_ACTIVE: "dockerized"
    profiles:
      - local
      - dockerized
networks:
  default: