version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${TYPE11_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TYPE11_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 1s
      timeout: 1s
      retries: 100
    user: postgres
  envoy:
    image: envoyproxy/envoy:dev-1ffd4522cdb86ac62ad307d8f28a166e5261411b
    ports:
      - "8080:8080"
      - "8081:8081"
      - "10000:10000"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      default:
  type-11:
    build:
      context: ./../../.
    ports:
      - "9090:9090"
    networks:
      default:
    depends_on:
      - postgres
    environment:
      TYPE11_POSTGRES_URL: "jdbc:postgresql://postgres:5432/postgres"
      TYPE11_POSTGRES_USER: ${TYPE11_POSTGRES_USER}
      TYPE11_POSTGRES_PASSWORD: ${TYPE11_POSTGRES_PASSWORD}
networks:
  default: